pattern_cols: 10              # 内角点列数（11列方格 → 10列角点）
pattern_rows: 7               # 内角点行数（8行方格 → 7行角点）
square_size_mm: 15            # 方格边长（毫米）

R_gimbal2imubody: [1, 0, 0, 0, 1, 0,  0, 0, 1]

camera_name: "hikrobot"
exposure_ms: 3
gain: 10.0
vid_pid: "2bdf:0001"

#####-----cboard参数-----#####
quaternion_canid: 0x01
bullet_speed_canid: 0x110
send_canid: 0xff
can_interface: "can0"

#####-----SerialIMU参数-----#####
serial_imu_port: "/dev/ttyACM0"
serial_imu_baudrate: 115200