# 机器人血量数据 (裁判系统串口协议 V1.2.0 0x0003)
# 2026 season update: only ally robots HP data

uint16 ally_1_robot_hp       # 己方 1 号英雄机器人血量，若该机器人未上场或者被罚下，则血量为 0
uint16 ally_2_robot_hp       # 己方 2 号工程机器人血量
uint16 ally_3_robot_hp       # 己方 3 号步兵机器人血量
uint16 ally_4_robot_hp       # 己方 4 号步兵机器人血量
uint16 ally_7_robot_hp       # 己方 7 号哨兵机器人血量
uint16 ally_outpost_hp       # 己方前哨站血量
uint16 ally_base_hp          # 己方基地血量